const express = require('express');
const router = express.Router();
const trabajoController = require('../controllers/trabajoController');
const {verifyToken, isColaborador, isContratista} = require('../../../middleware/authMiddleware');
router.post('/create',verifyToken, isContratista,trabajoController.createTrabajo);
router.get('/edit/:id', verifyToken, isContratista, trabajoController.getTrabajoById); 
router.get('/cercanos/:page',verifyToken, isColaborador, trabajoController.listTrabajosCercanos);
router.get('/ultimos/:page', verifyToken, isContratista, trabajoController.listUltimosTrabajosByContratista);
router.get('/buscar', verifyToken,isColaborador, trabajoController.getTrabajosByTitleAndLocation);
module.exports = router;